use std::{
    fs,
    io::{BufRead, IsTerminal, Write},
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, bail};

use crate::{
    doctor::{DoctorReport, Status, ToolStatus},
    shell::command_path,
};

const COMMON_BREW_PACKAGES: &[&str] = &[
    "gh", "tmux", "yq", "fzf", "direnv", "starship", "kubectl", "helm", "lazygit",
];
const COMMON_NPM_GLOBALS: &[&str] = &["wrangler"];
const COMMON_TOOL_NAMES: &[&str] = &[
    "fnm", "node", "npm", "pnpm", "yarn", "bun", "deno", "go", "rust", "uv", "python", "poetry",
    "ruby", "wrangler",
];

#[derive(Debug, Clone)]
pub struct InitDocument {
    pub content: String,
}

#[derive(Debug)]
pub struct InitWriteResult {
    pub path: PathBuf,
    pub overwritten: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InitDraft {
    pub policy: PolicyDraft,
    pub fnm: Option<SimpleToolDraft>,
    pub node: Option<NodeDraft>,
    pub npm: Option<SimpleToolDraft>,
    pub pnpm: Option<SimpleToolDraft>,
    pub yarn: Option<SimpleToolDraft>,
    pub bun: Option<SimpleToolDraft>,
    pub deno: Option<SimpleToolDraft>,
    pub go: Option<GoDraft>,
    pub rust: Option<RustDraft>,
    pub uv: Option<SimpleToolDraft>,
    pub python: Option<SimpleToolDraft>,
    pub poetry: Option<SimpleToolDraft>,
    pub ruby: Option<SimpleToolDraft>,
    pub wrangler: Option<SimpleToolDraft>,
    pub cli: Option<CliDraft>,
    pub homebrew: Option<HomebrewDraft>,
    pub npm_config: Option<NpmDraft>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PolicyDraft {
    pub channel: String,
    pub platform: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SimpleToolDraft {
    pub manager: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NodeDraft {
    pub version: String,
    pub manager: String,
    pub package_managers: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GoDraft {
    pub version: String,
    pub manager: String,
    pub source: String,
    pub install_dir: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RustDraft {
    pub channel: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CliDraft {
    pub manager: String,
    pub packages: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HomebrewDraft {
    pub packages: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NpmDraft {
    pub global_packages: Vec<String>,
}

pub fn build_init_draft(report: &DoctorReport) -> InitDraft {
    build_init_draft_with_inventory(
        report,
        detect_installed_commands(COMMON_BREW_PACKAGES),
        detect_installed_commands(COMMON_NPM_GLOBALS),
    )
}

fn build_init_draft_with_inventory(
    report: &DoctorReport,
    brew_packages: Vec<String>,
    npm_globals: Vec<String>,
) -> InitDraft {
    InitDraft {
        policy: PolicyDraft {
            channel: "stable".to_string(),
            platform: current_platform(),
        },
        fnm: detect_fnm(report),
        node: detect_node(report),
        npm: detect_latest_tool(report, "npm", "npm"),
        pnpm: detect_latest_tool(report, "pnpm", "corepack"),
        yarn: detect_latest_tool(report, "yarn", "corepack"),
        bun: detect_latest_tool(report, "bun", "brew"),
        deno: detect_deno(report),
        go: detect_go(report),
        rust: detect_rust(report),
        uv: detect_latest_tool(report, "uv", "standalone"),
        python: detect_homebrew_tool(report, "python"),
        poetry: detect_poetry(report),
        ruby: detect_homebrew_tool(report, "ruby"),
        wrangler: detect_latest_tool(report, "wrangler", "npm"),
        cli: (!brew_packages.is_empty()).then_some(CliDraft {
            manager: "brew".to_string(),
            packages: brew_packages.clone(),
        }),
        homebrew: (!brew_packages.is_empty()).then_some(HomebrewDraft {
            packages: brew_packages,
        }),
        npm_config: (!npm_globals.is_empty()).then_some(NpmDraft {
            global_packages: npm_globals,
        }),
    }
}

pub fn customize_init_draft_interactively(draft: &mut InitDraft) -> Result<bool> {
    if std::io::stdin().is_terminal() && std::io::stderr().is_terminal() {
        return crate::init_tui::customize_init_draft_tui(draft);
    }

    let stdin = std::io::stdin();
    let mut input = stdin.lock();
    let stderr = std::io::stderr();
    let mut output = stderr.lock();
    customize_init_draft_with_io(draft, &mut input, &mut output)
}

pub fn render_init_document(draft: &InitDraft) -> InitDocument {
    let mut sections = Vec::new();
    sections.push(
        "# Generated by `devkit init` from the current machine state.\n# Review and trim this file before using it as a team policy.".to_string(),
    );
    sections.push(render_policy_section(&draft.policy));

    if let Some(section) = render_simple_tool("fnm", draft.fnm.as_ref(), Some("latest")) {
        sections.push(section);
    }
    if let Some(section) = render_node_tool(draft.node.as_ref()) {
        sections.push(section);
    }
    if let Some(section) = render_simple_tool("npm", draft.npm.as_ref(), Some("latest")) {
        sections.push(section);
    }
    if let Some(section) = render_simple_tool("pnpm", draft.pnpm.as_ref(), Some("latest")) {
        sections.push(section);
    }
    if let Some(section) = render_simple_tool("yarn", draft.yarn.as_ref(), Some("stable")) {
        sections.push(section);
    }
    if let Some(section) = render_simple_tool("bun", draft.bun.as_ref(), Some("latest")) {
        sections.push(section);
    }
    if let Some(section) = render_simple_tool("deno", draft.deno.as_ref(), Some("latest")) {
        sections.push(section);
    }
    if let Some(section) = render_go_tool(draft.go.as_ref()) {
        sections.push(section);
    }
    if let Some(section) = render_rust_tool(draft.rust.as_ref()) {
        sections.push(section);
    }
    if let Some(section) = render_simple_tool("uv", draft.uv.as_ref(), Some("latest")) {
        sections.push(section);
    }
    if let Some(section) = render_simple_tool("python", draft.python.as_ref(), Some("latest")) {
        sections.push(section);
    }
    if let Some(section) = render_simple_tool("poetry", draft.poetry.as_ref(), Some("latest")) {
        sections.push(section);
    }
    if let Some(section) = render_simple_tool("ruby", draft.ruby.as_ref(), Some("latest")) {
        sections.push(section);
    }
    if let Some(section) = render_simple_tool("wrangler", draft.wrangler.as_ref(), Some("latest")) {
        sections.push(section);
    }
    if let Some(section) = render_cli_tool_section(draft.cli.as_ref()) {
        sections.push(section);
    }
    if let Some(section) = render_homebrew_section(draft.homebrew.as_ref()) {
        sections.push(section);
    }
    if let Some(section) = render_npm_section(draft.npm_config.as_ref()) {
        sections.push(section);
    }

    InitDocument {
        content: sections.join("\n\n") + "\n",
    }
}

pub fn write_init_document(
    path: &Path,
    force: bool,
    document: &InitDocument,
) -> Result<InitWriteResult> {
    let existed = path.exists();
    if existed && !force {
        bail!(
            "{} already exists; use --force to overwrite it",
            path.display()
        );
    }

    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
    {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    fs::write(path, &document.content)
        .with_context(|| format!("failed to write {}", path.display()))?;

    Ok(InitWriteResult {
        path: path.to_path_buf(),
        overwritten: existed,
    })
}

fn customize_init_draft_with_io<R: BufRead, W: Write>(
    draft: &mut InitDraft,
    input: &mut R,
    output: &mut W,
) -> Result<bool> {
    writeln!(
        output,
        "Interactive init. Press Enter to keep the detected default."
    )?;
    draft.policy.channel = prompt_text(output, input, "Policy channel", &draft.policy.channel)?;
    draft.policy.platform = prompt_text(output, input, "Target platform", &draft.policy.platform)?;

    let selected_tools = prompt_tool_selection(
        output,
        input,
        "Tool sections",
        &selected_tool_names(draft),
        COMMON_TOOL_NAMES,
    )?;
    apply_tool_selection(draft, &selected_tools);

    let missing_tools = missing_tool_names(draft);
    if !missing_tools.is_empty() {
        let additions = prompt_tool_selection(
            output,
            input,
            "Add missing tool sections",
            &[],
            &missing_tools,
        )?;
        for tool in additions {
            set_tool_enabled(draft, &tool, true);
        }
    }

    if prompt_yes_no(output, input, "Edit tool details?", false)? {
        prompt_selected_tool_details(output, input, draft)?;
    }

    prompt_cli_packages(output, input, &mut draft.cli, &mut draft.homebrew)?;
    prompt_npm_globals(output, input, &mut draft.npm_config)?;

    let document = render_init_document(draft);
    writeln!(output)?;
    writeln!(output, "Preview:\n")?;
    writeln!(output, "{}", document.content)?;
    prompt_yes_no(output, input, "Proceed with this config?", true)
}

fn prompt_selected_tool_details<R: BufRead, W: Write>(
    output: &mut W,
    input: &mut R,
    draft: &mut InitDraft,
) -> Result<()> {
    prompt_simple_tool(output, input, "fnm", &mut draft.fnm)?;
    prompt_node(output, input, &mut draft.node)?;
    prompt_simple_tool(output, input, "npm", &mut draft.npm)?;
    prompt_simple_tool(output, input, "pnpm", &mut draft.pnpm)?;
    prompt_simple_tool(output, input, "yarn", &mut draft.yarn)?;
    prompt_simple_tool(output, input, "bun", &mut draft.bun)?;
    prompt_simple_tool(output, input, "deno", &mut draft.deno)?;
    prompt_go(output, input, &mut draft.go)?;
    prompt_rust(output, input, &mut draft.rust)?;
    prompt_simple_tool(output, input, "uv", &mut draft.uv)?;
    prompt_simple_tool(output, input, "python", &mut draft.python)?;
    prompt_simple_tool(output, input, "poetry", &mut draft.poetry)?;
    prompt_simple_tool(output, input, "ruby", &mut draft.ruby)?;
    prompt_simple_tool(output, input, "wrangler", &mut draft.wrangler)?;

    Ok(())
}

fn prompt_tool_selection<R: BufRead, W: Write>(
    output: &mut W,
    input: &mut R,
    label: &str,
    default: &[String],
    choices: &[&str],
) -> Result<Vec<String>> {
    let default_text = if default.is_empty() {
        "none".to_string()
    } else {
        default.join(", ")
    };
    let choices_text = choices.join(", ");
    loop {
        writeln!(output, "{label} choices: {choices_text}")?;
        write!(
            output,
            "{label} [{default_text}] (comma-separated, `all`, `none`): "
        )?;
        output.flush()?;

        let line = read_line(input)?;
        let trimmed = line.trim();
        if trimmed.is_empty() {
            return Ok(default.to_vec());
        }
        if trimmed.eq_ignore_ascii_case("none") {
            return Ok(Vec::new());
        }
        if trimmed.eq_ignore_ascii_case("all") {
            return Ok(choices.iter().map(|tool| (*tool).to_string()).collect());
        }

        let mut selected = Vec::new();
        let mut unknown = Vec::new();
        for value in trimmed.split(',').map(str::trim) {
            if value.is_empty() {
                continue;
            }
            let normalized = value.to_ascii_lowercase();
            if choices.contains(&normalized.as_str()) {
                if !selected.contains(&normalized) {
                    selected.push(normalized);
                }
            } else {
                unknown.push(value.to_string());
            }
        }

        if unknown.is_empty() {
            return Ok(order_tool_names(selected, choices));
        }

        writeln!(
            output,
            "Unknown tool section(s): {}. Supported: {}",
            unknown.join(", "),
            choices_text
        )?;
    }
}

fn selected_tool_names(draft: &InitDraft) -> Vec<String> {
    COMMON_TOOL_NAMES
        .iter()
        .filter(|tool| tool_is_enabled(draft, tool))
        .map(|tool| (*tool).to_string())
        .collect()
}

fn missing_tool_names(draft: &InitDraft) -> Vec<&'static str> {
    COMMON_TOOL_NAMES
        .iter()
        .copied()
        .filter(|tool| !tool_is_enabled(draft, tool))
        .collect()
}

fn apply_tool_selection(draft: &mut InitDraft, selected: &[String]) {
    for &tool in COMMON_TOOL_NAMES {
        set_tool_enabled(
            draft,
            tool,
            selected.iter().any(|selected| selected == tool),
        );
    }
}

fn order_tool_names(selected: Vec<String>, choices: &[&str]) -> Vec<String> {
    choices
        .iter()
        .filter(|tool| selected.iter().any(|selected| selected == **tool))
        .map(|tool| (*tool).to_string())
        .collect()
}

fn tool_is_enabled(draft: &InitDraft, tool: &str) -> bool {
    match tool {
        "fnm" => draft.fnm.is_some(),
        "node" => draft.node.is_some(),
        "npm" => draft.npm.is_some(),
        "pnpm" => draft.pnpm.is_some(),
        "yarn" => draft.yarn.is_some(),
        "bun" => draft.bun.is_some(),
        "deno" => draft.deno.is_some(),
        "go" => draft.go.is_some(),
        "rust" => draft.rust.is_some(),
        "uv" => draft.uv.is_some(),
        "python" => draft.python.is_some(),
        "poetry" => draft.poetry.is_some(),
        "ruby" => draft.ruby.is_some(),
        "wrangler" => draft.wrangler.is_some(),
        _ => false,
    }
}

fn set_tool_enabled(draft: &mut InitDraft, tool: &str, enabled: bool) {
    match tool {
        "fnm" => set_simple_tool(&mut draft.fnm, enabled, "brew"),
        "node" => {
            if enabled {
                draft.node.get_or_insert_with(default_node_draft);
            } else {
                draft.node = None;
            }
        }
        "npm" => set_simple_tool(&mut draft.npm, enabled, "npm"),
        "pnpm" => set_simple_tool(&mut draft.pnpm, enabled, "corepack"),
        "yarn" => set_simple_tool(&mut draft.yarn, enabled, "corepack"),
        "bun" => set_simple_tool(&mut draft.bun, enabled, "brew"),
        "deno" => set_simple_tool(&mut draft.deno, enabled, "brew"),
        "go" => {
            if enabled {
                draft.go.get_or_insert_with(default_go_draft);
            } else {
                draft.go = None;
            }
        }
        "rust" => {
            if enabled {
                draft.rust.get_or_insert_with(default_rust_draft);
            } else {
                draft.rust = None;
            }
        }
        "uv" => set_simple_tool(&mut draft.uv, enabled, "standalone"),
        "python" => set_simple_tool(&mut draft.python, enabled, "brew"),
        "poetry" => set_simple_tool(&mut draft.poetry, enabled, "brew"),
        "ruby" => set_simple_tool(&mut draft.ruby, enabled, "brew"),
        "wrangler" => set_simple_tool(&mut draft.wrangler, enabled, "npm"),
        _ => {}
    }
}

fn set_simple_tool(tool: &mut Option<SimpleToolDraft>, enabled: bool, default_manager: &str) {
    if enabled {
        tool.get_or_insert_with(|| SimpleToolDraft {
            manager: default_manager.to_string(),
        });
    } else {
        *tool = None;
    }
}

fn default_node_draft() -> NodeDraft {
    NodeDraft {
        version: "stable".to_string(),
        manager: "fnm".to_string(),
        package_managers: vec![
            "npm".to_string(),
            "pnpm".to_string(),
            "yarn".to_string(),
            "bun".to_string(),
        ],
    }
}

fn default_go_draft() -> GoDraft {
    GoDraft {
        version: "stable".to_string(),
        manager: "brew".to_string(),
        source: "brew".to_string(),
        install_dir: None,
    }
}

fn default_rust_draft() -> RustDraft {
    RustDraft {
        channel: "stable".to_string(),
    }
}

fn prompt_simple_tool<R: BufRead, W: Write>(
    output: &mut W,
    input: &mut R,
    name: &str,
    tool: &mut Option<SimpleToolDraft>,
) -> Result<()> {
    let Some(current) = tool.clone() else {
        return Ok(());
    };
    let manager = prompt_text(
        output,
        input,
        &format!("{name} manager"),
        current.manager.as_str(),
    )?;
    *tool = Some(SimpleToolDraft { manager });
    Ok(())
}

fn prompt_node<R: BufRead, W: Write>(
    output: &mut W,
    input: &mut R,
    node: &mut Option<NodeDraft>,
) -> Result<()> {
    let Some(current) = node.clone() else {
        return Ok(());
    };
    let version = prompt_text(output, input, "Node version", &current.version)?;
    let manager = prompt_text(output, input, "Node manager", &current.manager)?;
    let package_managers = prompt_list(
        output,
        input,
        "Node package managers",
        &current.package_managers,
    )?;
    *node = Some(NodeDraft {
        version,
        manager,
        package_managers,
    });
    Ok(())
}

fn prompt_go<R: BufRead, W: Write>(
    output: &mut W,
    input: &mut R,
    go: &mut Option<GoDraft>,
) -> Result<()> {
    let Some(current) = go.clone() else {
        return Ok(());
    };
    let version = prompt_text(output, input, "Go version", &current.version)?;
    let manager = prompt_text(output, input, "Go manager", &current.manager)?;
    let source = prompt_text(output, input, "Go source", &current.source)?;
    let install_dir = if source == "official" {
        Some(prompt_text(
            output,
            input,
            "Go install directory",
            current
                .install_dir
                .as_deref()
                .unwrap_or("~/.local/opt/go/current"),
        )?)
    } else {
        None
    };

    *go = Some(GoDraft {
        version,
        manager,
        source,
        install_dir,
    });
    Ok(())
}

fn prompt_rust<R: BufRead, W: Write>(
    output: &mut W,
    input: &mut R,
    rust: &mut Option<RustDraft>,
) -> Result<()> {
    let Some(current) = rust.clone() else {
        return Ok(());
    };
    let channel = prompt_text(output, input, "Rust channel", &current.channel)?;
    *rust = Some(RustDraft { channel });
    Ok(())
}

fn prompt_cli_packages<R: BufRead, W: Write>(
    output: &mut W,
    input: &mut R,
    cli: &mut Option<CliDraft>,
    homebrew: &mut Option<HomebrewDraft>,
) -> Result<()> {
    let default_packages = cli
        .as_ref()
        .map(|cli| cli.packages.clone())
        .unwrap_or_default();
    let packages = prompt_list(output, input, "Homebrew CLI packages", &default_packages)?;

    if packages.is_empty() {
        *cli = None;
        *homebrew = None;
        return Ok(());
    }

    *cli = Some(CliDraft {
        manager: "brew".to_string(),
        packages: packages.clone(),
    });
    *homebrew = Some(HomebrewDraft { packages });
    Ok(())
}

fn prompt_npm_globals<R: BufRead, W: Write>(
    output: &mut W,
    input: &mut R,
    npm_config: &mut Option<NpmDraft>,
) -> Result<()> {
    let default_packages = npm_config
        .as_ref()
        .map(|npm| npm.global_packages.clone())
        .unwrap_or_default();
    let packages = prompt_list(output, input, "npm global packages", &default_packages)?;
    if packages.is_empty() {
        *npm_config = None;
    } else {
        *npm_config = Some(NpmDraft {
            global_packages: packages,
        });
    }
    Ok(())
}

fn prompt_text<R: BufRead, W: Write>(
    output: &mut W,
    input: &mut R,
    label: &str,
    default: &str,
) -> Result<String> {
    write!(output, "{label} [{default}]: ")?;
    output.flush()?;

    let line = read_line(input)?;
    let trimmed = line.trim();
    if trimmed.is_empty() {
        Ok(default.to_string())
    } else {
        Ok(trimmed.to_string())
    }
}

fn prompt_yes_no<R: BufRead, W: Write>(
    output: &mut W,
    input: &mut R,
    label: &str,
    default: bool,
) -> Result<bool> {
    let suffix = if default { "[Y/n]" } else { "[y/N]" };
    loop {
        write!(output, "{label} {suffix}: ")?;
        output.flush()?;

        let line = read_line(input)?;
        let trimmed = line.trim().to_ascii_lowercase();
        if trimmed.is_empty() {
            return Ok(default);
        }
        match trimmed.as_str() {
            "y" | "yes" => return Ok(true),
            "n" | "no" => return Ok(false),
            _ => {
                writeln!(output, "Please answer yes or no.")?;
            }
        }
    }
}

fn prompt_list<R: BufRead, W: Write>(
    output: &mut W,
    input: &mut R,
    label: &str,
    default: &[String],
) -> Result<Vec<String>> {
    let default_text = if default.is_empty() {
        "none".to_string()
    } else {
        default.join(", ")
    };
    write!(
        output,
        "{label} [{default_text}] (comma-separated, `none` to clear): "
    )?;
    output.flush()?;

    let line = read_line(input)?;
    let trimmed = line.trim();
    if trimmed.is_empty() {
        return Ok(default.to_vec());
    }
    if trimmed.eq_ignore_ascii_case("none") {
        return Ok(Vec::new());
    }

    Ok(trimmed
        .split(',')
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(ToString::to_string)
        .collect())
}

fn read_line<R: BufRead>(input: &mut R) -> Result<String> {
    let mut line = String::new();
    let bytes = input.read_line(&mut line)?;
    if bytes == 0 {
        bail!("stdin closed while reading interactive input");
    }
    Ok(line)
}

fn render_policy_section(policy: &PolicyDraft) -> String {
    format!(
        "[policy]\nchannel = {}\nplatform = {}",
        toml_string(&policy.channel),
        toml_string(&policy.platform)
    )
}

fn render_simple_tool(
    name: &str,
    tool: Option<&SimpleToolDraft>,
    version: Option<&str>,
) -> Option<String> {
    let tool = tool?;
    let mut lines = vec![format!("[tools.{name}]")];
    if let Some(version) = version {
        lines.push(format!("version = {}", toml_string(version)));
    }
    lines.push(format!("manager = {}", toml_string(&tool.manager)));
    Some(lines.join("\n"))
}

fn render_node_tool(node: Option<&NodeDraft>) -> Option<String> {
    let node = node?;
    let mut lines = vec![
        "[tools.node]".to_string(),
        format!("version = {}", toml_string(&node.version)),
        format!("manager = {}", toml_string(&node.manager)),
    ];
    if !node.package_managers.is_empty() {
        lines.push(format!(
            "package_managers = [{}]",
            quoted_list(&node.package_managers)
        ));
    }
    Some(lines.join("\n"))
}

fn render_go_tool(go: Option<&GoDraft>) -> Option<String> {
    let go = go?;
    let mut lines = vec![
        "[tools.go]".to_string(),
        format!("version = {}", toml_string(&go.version)),
        format!("manager = {}", toml_string(&go.manager)),
        format!("source = {}", toml_string(&go.source)),
    ];
    if let Some(install_dir) = &go.install_dir {
        lines.push(format!("install_dir = {}", toml_string(install_dir)));
    }
    Some(lines.join("\n"))
}

fn render_rust_tool(rust: Option<&RustDraft>) -> Option<String> {
    let rust = rust?;
    Some(format!(
        "[tools.rustc]\nversion = {}\nmanager = \"rustup\"\n\n[tools.cargo]\nversion = {}\nmanager = \"rustup\"",
        toml_string(&rust.channel),
        toml_string(&rust.channel)
    ))
}

fn render_cli_tool_section(cli: Option<&CliDraft>) -> Option<String> {
    let cli = cli?;
    if cli.packages.is_empty() {
        return None;
    }
    Some(format!(
        "[tools.cli]\nmanager = {}\npackages = [{}]",
        toml_string(&cli.manager),
        quoted_list(&cli.packages)
    ))
}

fn render_homebrew_section(homebrew: Option<&HomebrewDraft>) -> Option<String> {
    let homebrew = homebrew?;
    if homebrew.packages.is_empty() {
        return None;
    }
    Some(format!(
        "[homebrew]\npackages = [{}]",
        quoted_list(&homebrew.packages)
    ))
}

fn render_npm_section(npm: Option<&NpmDraft>) -> Option<String> {
    let npm = npm?;
    if npm.global_packages.is_empty() {
        return None;
    }
    Some(format!(
        "[npm]\nglobal_packages = [{}]",
        quoted_list(&npm.global_packages)
    ))
}

fn detect_fnm(report: &DoctorReport) -> Option<SimpleToolDraft> {
    let tool = installed_tool(report, "fnm")?;
    if path_contains(tool, "/homebrew/") || path_contains(tool, "/opt/homebrew/") {
        return Some(SimpleToolDraft {
            manager: "brew".to_string(),
        });
    }
    None
}

fn detect_node(report: &DoctorReport) -> Option<NodeDraft> {
    let tool = installed_tool(report, "node")?;
    let manager = if path_contains(tool, "fnm") {
        "fnm"
    } else if path_contains(tool, "/homebrew/")
        || path_contains(tool, "/opt/homebrew/")
        || path_contains(tool, "/usr/local/")
    {
        "brew"
    } else {
        return None;
    };
    let version = node_policy_version(tool.current.as_deref()?);

    Some(NodeDraft {
        version,
        manager: manager.to_string(),
        package_managers: vec!["npm".to_string(), "pnpm".to_string(), "bun".to_string()],
    })
}

fn detect_go(report: &DoctorReport) -> Option<GoDraft> {
    let tool = installed_tool(report, "go")?;
    let version = tool.current.as_deref()?.to_string();
    let path = tool.path.as_ref()?;

    if path_contains(tool, "/homebrew/") || path_contains(tool, "/opt/homebrew/") {
        return Some(GoDraft {
            version,
            manager: "brew".to_string(),
            source: "brew".to_string(),
            install_dir: None,
        });
    }

    let install_dir = path.parent()?.parent()?.display().to_string();
    Some(GoDraft {
        version,
        manager: "official".to_string(),
        source: "official".to_string(),
        install_dir: Some(install_dir),
    })
}

fn detect_rust(report: &DoctorReport) -> Option<RustDraft> {
    let rustc = installed_tool(report, "rustc")?;
    if !path_contains(rustc, "cargo") && !path_contains(rustc, "rustup") {
        return None;
    }
    Some(RustDraft {
        channel: "stable".to_string(),
    })
}

fn detect_latest_tool(report: &DoctorReport, name: &str, manager: &str) -> Option<SimpleToolDraft> {
    installed_tool(report, name)?;
    Some(SimpleToolDraft {
        manager: manager.to_string(),
    })
}

fn detect_homebrew_tool(report: &DoctorReport, name: &str) -> Option<SimpleToolDraft> {
    let tool = installed_tool(report, name)?;
    is_homebrew_tool(tool).then_some(SimpleToolDraft {
        manager: "brew".to_string(),
    })
}

fn detect_deno(report: &DoctorReport) -> Option<SimpleToolDraft> {
    let tool = installed_tool(report, "deno")?;
    Some(SimpleToolDraft {
        manager: if is_homebrew_tool(tool) {
            "brew".to_string()
        } else {
            "standalone".to_string()
        },
    })
}

fn detect_poetry(report: &DoctorReport) -> Option<SimpleToolDraft> {
    let tool = installed_tool(report, "poetry")?;
    Some(SimpleToolDraft {
        manager: if is_homebrew_tool(tool) {
            "brew".to_string()
        } else {
            "official".to_string()
        },
    })
}

fn installed_tool<'a>(report: &'a DoctorReport, name: &str) -> Option<&'a ToolStatus> {
    report
        .tools
        .iter()
        .find(|tool| tool.name == name && !matches!(tool.status, Status::Missing))
}

fn detect_installed_commands(commands: &[&str]) -> Vec<String> {
    commands
        .iter()
        .filter(|command| command_path(command).is_some())
        .map(|command| (*command).to_string())
        .collect()
}

fn quoted_list(items: &[String]) -> String {
    items
        .iter()
        .map(|item| toml_string(item))
        .collect::<Vec<_>>()
        .join(", ")
}

fn toml_string(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len() + 2);
    escaped.push('"');
    for character in value.chars() {
        match character {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\r' => escaped.push_str("\\r"),
            '\t' => escaped.push_str("\\t"),
            character if character.is_control() => {
                escaped.push_str(&format!("\\u{:04X}", character as u32));
            }
            character => escaped.push(character),
        }
    }
    escaped.push('"');
    escaped
}

fn node_policy_version(version: &str) -> String {
    match version.split('.').next() {
        Some(major) if !major.is_empty() => format!("{major}.x"),
        _ => version.to_string(),
    }
}

fn current_platform() -> String {
    let arch = match std::env::consts::ARCH {
        "aarch64" => "arm64",
        other => other,
    };
    format!("{}-{arch}", std::env::consts::OS)
}

fn is_homebrew_tool(tool: &ToolStatus) -> bool {
    path_contains(tool, "/homebrew/")
        || path_contains(tool, "/opt/homebrew/")
        || path_contains(tool, "/usr/local/")
}

fn path_contains(tool: &ToolStatus, pattern: &str) -> bool {
    tool.path
        .as_ref()
        .is_some_and(|path| path.to_string_lossy().contains(pattern))
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        io::Cursor,
        path::PathBuf,
        time::{SystemTime, UNIX_EPOCH},
    };

    use crate::doctor::{DoctorReport, Status, ToolStatus};

    use super::{
        build_init_draft_with_inventory, customize_init_draft_with_io, render_init_document,
        write_init_document,
    };

    #[test]
    fn generates_core_tool_sections() {
        let report = DoctorReport {
            tools: vec![
                installed_tool("fnm", "/opt/homebrew/bin/fnm", "1.39.0"),
                installed_tool(
                    "node",
                    "/Users/test/.local/state/fnm_multishells/1/bin/node",
                    "24.15.0",
                ),
                installed_tool("npm", "/tmp/npm", "11.13.0"),
                installed_tool("pnpm", "/tmp/pnpm", "10.33.2"),
                installed_tool("yarn", "/tmp/yarn", "4.12.0"),
                installed_tool("bun", "/opt/homebrew/bin/bun", "1.3.13"),
                installed_tool("deno", "/opt/homebrew/bin/deno", "2.5.6"),
                installed_tool("uv", "/Users/test/.local/bin/uv", "0.11.7"),
                installed_tool("python", "/opt/homebrew/bin/python3", "3.13.4"),
                installed_tool("poetry", "/Users/test/.local/bin/poetry", "2.3.1"),
                installed_tool("ruby", "/opt/homebrew/bin/ruby", "3.4.1"),
                installed_tool("wrangler", "/tmp/wrangler", "4.85.0"),
                installed_tool("rustc", "/Users/test/.cargo/bin/rustc", "1.95.0"),
                installed_tool("cargo", "/Users/test/.cargo/bin/cargo", "1.95.0"),
                installed_tool("go", "/Users/test/.local/opt/go/current/bin/go", "1.26.2"),
            ],
            issues: vec![],
        };

        let document = render_init_document(&build_init_draft_with_inventory(
            &report,
            Vec::new(),
            Vec::new(),
        ));

        assert!(document.content.contains("[policy]"));
        assert!(document.content.contains("[tools.node]"));
        assert!(document.content.contains("version = \"24.x\""));
        assert!(document.content.contains("[tools.yarn]"));
        assert!(document.content.contains("[tools.deno]"));
        assert!(document.content.contains("[tools.python]"));
        assert!(document.content.contains("[tools.poetry]"));
        assert!(document.content.contains("manager = \"official\""));
        assert!(document.content.contains("[tools.ruby]"));
        assert!(document.content.contains("[tools.go]"));
        assert!(
            document
                .content
                .contains("install_dir = \"/Users/test/.local/opt/go/current\"")
        );
        assert!(document.content.contains("[tools.rustc]"));
        assert!(document.content.contains("[tools.cargo]"));
    }

    #[test]
    fn interactive_customization_updates_draft() {
        let report = DoctorReport {
            tools: vec![
                installed_tool("node", "/Users/test/.local/state/fnm/bin/node", "24.15.0"),
                installed_tool("go", "/Users/test/.local/opt/go/current/bin/go", "1.26.2"),
            ],
            issues: vec![],
        };
        let mut draft = build_init_draft_with_inventory(&report, Vec::new(), Vec::new());
        let mut input = Cursor::new(
            [
                "beta",      // channel
                "",          // platform
                "",          // tool sections
                "",          // add missing tool sections
                "y",         // edit tool details
                "26.x",      // node version
                "fnm",       // node manager
                "npm, pnpm", // package managers
                "1.26.3",    // go version
                "brew",      // go manager
                "brew",      // go source
                "none",      // cli packages
                "none",      // npm globals
                "y",         // confirm
            ]
            .join("\n")
                + "\n",
        );
        let mut output = Vec::new();

        let confirmed = customize_init_draft_with_io(&mut draft, &mut input, &mut output).unwrap();
        let document = render_init_document(&draft);

        assert!(confirmed);
        assert_eq!(draft.policy.channel, "beta");
        assert!(draft.node.is_some());
        assert_eq!(draft.node.as_ref().unwrap().version, "26.x");
        assert_eq!(
            draft.node.as_ref().unwrap().package_managers,
            vec!["npm".to_string(), "pnpm".to_string()]
        );
        assert_eq!(draft.go.as_ref().unwrap().manager, "brew");
        assert_eq!(draft.go.as_ref().unwrap().source, "brew");
        assert!(draft.go.as_ref().unwrap().install_dir.is_none());
        assert!(draft.rust.is_none());
        assert!(draft.cli.is_none());
        assert!(draft.homebrew.is_none());
        assert!(!document.content.contains("[tools.rustc]"));
        assert!(!document.content.contains("[homebrew]"));
    }

    #[test]
    fn interactive_customization_can_add_missing_tool() {
        let report = DoctorReport {
            tools: vec![],
            issues: vec![],
        };
        let mut draft = build_init_draft_with_inventory(&report, Vec::new(), Vec::new());
        let mut input = Cursor::new(
            [
                "",     // channel
                "",     // platform
                "",     // tool sections
                "deno", // add missing tool sections
                "",     // edit tool details
                "",     // cli packages
                "",     // npm globals
                "y",    // confirm
            ]
            .join("\n")
                + "\n",
        );
        let mut output = Vec::new();

        let confirmed = customize_init_draft_with_io(&mut draft, &mut input, &mut output).unwrap();
        let document = render_init_document(&draft);

        assert!(confirmed);
        assert_eq!(draft.deno.as_ref().unwrap().manager, "brew");
        assert!(document.content.contains("[tools.deno]"));
        assert!(document.content.contains("manager = \"brew\""));
    }

    #[test]
    fn escapes_interactive_toml_strings() {
        let draft = super::InitDraft {
            policy: super::PolicyDraft {
                channel: "stable\"quoted".to_string(),
                platform: "macos\\arm64".to_string(),
            },
            fnm: Some(super::SimpleToolDraft {
                manager: "brew\"tap".to_string(),
            }),
            node: None,
            npm: None,
            pnpm: None,
            yarn: None,
            bun: None,
            deno: None,
            go: None,
            rust: None,
            uv: None,
            python: None,
            poetry: None,
            ruby: None,
            wrangler: None,
            cli: Some(super::CliDraft {
                manager: "brew".to_string(),
                packages: vec!["quoted\"package".to_string()],
            }),
            homebrew: None,
            npm_config: None,
        };

        let document = render_init_document(&draft);

        toml::from_str::<toml::Value>(&document.content).unwrap();
        assert!(document.content.contains("stable\\\"quoted"));
        assert!(document.content.contains("macos\\\\arm64"));
        assert!(document.content.contains("quoted\\\"package"));
    }

    #[test]
    fn writes_document_and_requires_force_for_overwrite() {
        let path = unique_temp_path("devkit-init");
        let document = super::InitDocument {
            content: "[policy]\nchannel = \"stable\"\n".to_string(),
        };

        let first = write_init_document(&path, false, &document).unwrap();
        assert!(!first.overwritten);
        assert_eq!(fs::read_to_string(&path).unwrap(), document.content);

        let error = write_init_document(&path, false, &document).unwrap_err();
        assert!(error.to_string().contains("already exists"));

        let second = write_init_document(&path, true, &document).unwrap();
        assert!(second.overwritten);

        let _ = fs::remove_file(path);
    }

    fn installed_tool(name: &str, path: &str, version: &str) -> ToolStatus {
        ToolStatus {
            name: name.to_string(),
            command: name.to_string(),
            path: Some(PathBuf::from(path)),
            current: Some(version.to_string()),
            required: None,
            manager: None,
            status: Status::Ok,
            note: None,
        }
    }

    fn unique_temp_path(prefix: &str) -> PathBuf {
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!("{prefix}-{timestamp}.toml"))
    }
}
